### ISSUE TITLE
Issue installing mapsf

### ISSUE THREAD

**Issue by sylsta** [riatelab/mapsf#4]
Hello, 
I can't manage to install the mapfs library on a fresh R and R studio setup. (Debian 10).

>\> install.packages("mapsf")
[...]
installing to /home/sylvain/.R/x86_64-pc-linux-gnu-library/3.5/mapsf/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error : object ‘hcl.colors’ is not exported by 'namespace:grDevices'
ERROR: lazy loading failed for package ‘mapsf’
\* removing ‘/home/sylvain/.R/x86_64-pc-linux-gnu-library/3.5/mapsf’
Warning in install.packages :
  installation of package ‘mapsf’ had non-zero exit status
Has anyone ever encountered this problem before? 

I did some research but without finding a solution. I am open to any suggestion.
All the best, 
Sylvain

**Comment by sylsta** [comment]
I finally found the solution. It turns out that the version of R proposed by debian is too old (<3.6)).
After adding the 'R-cran' repository, my version is updated, everything works !

https://stackoverflow.com/questions/65993395/rgl-package-has-non-zero-status
https://linuxize.com/post/how-to-install-r-on-debian-10/

My apologies for the inconvenience. I don't know R very well. Maybe there is a possibility to indicate a minimum version required to install a library?
Have a nice day.

**Comment by dieghernan** [comment]
@rCarto update this?

https://github.com/riatelab/mapsf/blob/e5a1ab6949cfa9896312056b7a7d5cffb9d96ec2/DESCRIPTION#L28

**Comment by dieghernan** [comment]
So I am run R CMD CHECK via GitHub Actions (https://github.com/dieghernan/mapsf/actions/runs/632996679) and  I think the problem is [(see check in R 3.5)](https://github.com/dieghernan/mapsf/runs/2058388611?check_suite_focus=true):
```
Error : object ‘hcl.colors’ is not exported by 'namespace:grDevices'
```

This object was [introduced in R 3.6](https://developer.r-project.org/Blog/public/2019/04/01/hcl-based-color-palettes-in-grdevices/) so I think the minimal version should be increased.

@rCarto macOS issues are due the `units` package was not available for macOS-oldrel (when the a package has been recently updated macOS fails until CRAN builds the binaries) and the other is a test, but I can’t understand why.

**Comment by dieghernan** [comment]
Good catch  @sylsta 👍🏻

**Comment by rCarto** [comment]
> @rCarto update this?
> 
> https://github.com/riatelab/mapsf/blob/e5a1ab6949cfa9896312056b7a7d5cffb9d96ec2/DESCRIPTION#L28

Yes, I will update the version number.

Concerning macos issues, the first one about `units` is out of the scope of the package. It may worth looking at sf ci config to check how it's done there. About the failed tests I'll have a look at the logs but I have close to zero knowledge on macos...

Thank you both anyway👍
